sudo: required
dist: bionic
service: docker
env:
  matrix:
    # travis + jsk jenkins
    - ROS_DISTRO=hydro   DOCKER_IMAGE=ubuntu:12.04
    - ROS_DISTRO=indigo  DOCKER_IMAGE=ubuntu:14.04
    - ROS_DISTRO=kinetic DOCKER_IMAGE=ubuntu:16.04
    - ROS_DISTRO=melodic DOCKER_IMAGE=ubuntu:18.04
script: # All commands must exit with code 0 on success. Anything else is considered failure.
  - docker run --rm -v $(pwd):/root/ -e ROS_DISTRO -ti $DOCKER_IMAGE /bin/bash -c "cd /root/; source ./.travis.sh | grep -v '\(Preparing to\|Selecting previously\|Setting up\|Unpacking \|Processing \|Collada \)' | grep -v '\(Joint\|Segment\) node' | grep -v -- '-- \(Up-to-date\|Installing\|Set runtime path\|Removed\)' | grep -v '^Scanning dependencies' | grep -v '%] \(Generating\|Building\)'" | sed 's/\x1b\[.*]*//g' | sed '/^$/d'

